# Generated by Django 2.1.5 on 2019-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20190128_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
